### ISSUE TITLE
SignUp

### ISSUE THREAD

**Issue by webbeloz** [ranjit95s/Twitter-r95s#1]
LogIn ok, Message ok, but SignUp it does't work.
is it possible to see your Sql database file?

**Comment by ranjit95s** [comment]
> LogIn ok, Message ok, but SignUp it does't work. is it possible to see your Sql database file?
[test.zip](https://github.com/ranjit95s/Twitter-r95s/files/10097833/test.zip)
PASSWORD: ranjit95s

**Comment by ranjit95s** [comment]
> LogIn ok, Message ok, but SignUp it does't work. is it possible to see your Sql database file?

i have changed ports numbers so many time. thats why we have to alter every single links in files too

**Comment by Bhawani1999** [comment]
![Screenshot 2023-07-18 233456](https://github.com/ranjit95s/Twitter-r95s/assets/58848743/4ee360a7-9176-45d8-a1bb-c8bf0de5ffe1)
